# Generated by Django 5.1.3 on 2024-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="txid",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="label",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["txid"], name="api_transac_txid_a6320a_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["wallet"], name="api_transac_wallet__280e1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["amount"], name="api_transac_amount_b70359_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["label"], name="api_wallet_label_612641_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["balance"], name="api_wallet_balance_c81ede_idx"
            ),
        ),
    ]
